providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./dns
    enforce_order: False
  cf-prod:
    class: octodns_cloudflare.CloudflareProvider
    account_id: "33e6189a4a87f1923e71af8da171e2ed"
    email: env/CLOUDFLARE_EMAIL
    token: env/CLOUDFLARE_GLOBAL_API_KEY
    #main_ttl: 120
  cf-sandbox:
    class: octodns_cloudflare.CloudflareProvider
    account_id: "dfa4ffaeef6265e4a8d18cffc5239754"
    email: env/CLOUDFLARE_EMAIL
    token: env/CLOUDFLARE_GLOBAL_API_KEY
    #main_ttl: 120

zones:
  recaptime.dev.:
    sources: [config]
    targets: [cf-prod]
  recaptime.eu.org.:
    sources: [config]
    targets: [cf-prod]
  lorebooks.eu.org.:
    sources: [config]
    targets: [cf-prod]