name: General Infrastructure Requests
title: "[infra] "
description: Submit a generat infrastructure request for those without specific issue forms/template.
assignees: [ajhalili2006,RecapTimeBot]
type: Task
body:
  - type: markdown
    attributes:
      value: |
        Use this issue form to submit requests relating to our Infrastructure (e.g., CI/CD, cloud resources,
        secrets/API keys, etc.). Note that this is not for requesting access to our infrastructure, but rather
        for provisioning resources or changing the configuration/environment. 
  - id: type
    type: dropdown
    attributes:
      label: Request Type
      description: Select the type of infrastructure request you are making.
      options:
        - Secrets/Key Management
        - IaaC Configuration
        - DNS Management
        - Cloud Resources
        - API Access
        - Others
    validations:
      required: true
  - id: is_crew
    type: dropdown
    attributes:
      label: "Are you either a @recaptime-dev/squad team member or community maintainer?"
      description: "If neither of these, your request might be rejected or take longer to review."
      options:
      - "Yes, I am a RecapTime.dev team member"
      - "Yes, I am an community maintainer (including HCB team and trusted community members)"
      - "No, I am neither of those"
  - id: description
    type: textarea
    attributes:
      label: About this request
      description: "Please describe your request as much as possible. You may mention other issues in this field as needed."
    validations:
      required: true
