name: Request GitHub organization admin support
description: >-
  Use this form for requesting help from an organization admin regarding your
  repository. Not for debugging/code review unless it is CI related.
title: '[repo-support]:'
assignees:
- ajhalili2006
labels:
- github-admin-support
- infra
body:
  - type: input
    id: repo
    attributes:
      label: Target repository for this request
      description: Please use the full repository URL to help us triage this issue easily.
      placeholder: https://github.com/recaptime-dev/repo-name
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: About this issue
      description: >-
        Please describe your issue, and why you need a specific action from
        someone with org admin permissions in GitHub.
    validations:
      required: true
  - type: textarea
    id: relatedIssues
    attributes:
      label: Related issues / Prior art
      description: If none, feel free to skip this field.
  - type: markdown
    attributes:
      value: >-
        This template was generated with [Issue Forms
        Creator](https://issue-forms-creator.netlify.app)
